name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  zstdTag:
    description: zstdTag
    required: true
    default: 'v1.5.7'
  zstdFileName:
    description: zstdFileName
    required: true
    default: 'zstd-v1.5.7-win64.zip'
  cleanCwd:
    description: cleanCwd
    required: false
  cleanPaths:
    description: cleanPaths
    required: false

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
