name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  dir:
    description: dir
    required: true
  outputPath:
    description: outputPath
    required: true

  cleanPaths:
    description: cleanPaths
    required: false
  zstdLevel:
    description: zstdLevel
    default: '19'
  chunkSize:
    description: chunkSize
    default: '2GB'
# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.mjs
